name: cicd workflow

on:
  push:
    branches:
      - main  
  workflow_dispatch:

env:
  docker_username: chedi1
  docker_image_name: spring
  docker_image_tag: v1.0.0

jobs:
  build-and-push-to-docker-hub:
    name: build and push to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'main'
          owner: 'chedipfe'
          repository: 'spring'

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.docker_username }}/${{ env.docker_image_name }}:${{ env.docker_image_tag }}
          context: ./spring